name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x


    - name: Install global packages
      run: npm install -g cordova @angular/cli @ionic/cli

    - name: Install dependencies
      run: npm install
      
    - name: Build android
      run: npm run android-build
      
    - name: Upload APK
      uses: actions/upload-artifact@v2.2.4
      with:
        name: app-debug.apk
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: warn
