name: Docker Image CI

on:
  push:
    tags:
      - '*'
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install global packages
        run: npm install -g cordova @angular/cli @ionic/cli
      - name: Install dependencies
        run: npm install
      - name: Build webapp
        run: npm run build
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag lukaspanni/wuerfelblock:$(date +%s)

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: lukaspanni
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            lukaspanni/wuerfelblock
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
