name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install global packages
      run: npm install -g cordova @angular/cli @ionic/cli
    - name: Install dependencies
      run: npm install
    - name: Build webapp
      run: npm run build
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lukaspanni/wuerfelblock:$(date +%s)
     
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: lukaspanni
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: lukaspanni/wuerfelblock:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

