name: Docker Image CI

on:
  push:
    tags:
      - '*'
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install global packages
        run: npm install -g cordova @angular/cli @ionic/cli
      - name: Install dependencies
        run: npm install
      - name: Build webapp
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: lukaspanni
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            lukaspanni/wuerfelblock
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ (github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags/') }}
            type=raw,value=stable,enable=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-docker
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deployment
        env:
          GH_TOKEN: ${{ secrets.CD_TOKEN }}
        run: |
          gh api repos/lukaspanni/infrastructure/dispatches --input - <<< '{"event_type": "${{ github.event.repository.name }}", "client_payload": { "kubernetes-config": "wuerfelblock.yml", "image-name": "ghcr.io/lukaspanni/wuerfelblock", "image-sha": "${{ github.sha }}" }'
